### ISSUE TITLE
feature request: scroll through system tray icons

### ISSUE THREAD

**Issue by twonth** [mydockfinder/mydockfinder#370]
I have so many tools installed that there are more entries in the system tray menu than can be shown on the screen at once. 

![image](https://user-images.githubusercontent.com/6320070/164866875-7d2afe6a-3986-40ef-8bf6-1e19d668eee5.png)

The final items on the list are simply cut off, with no way to view them. 

Can you implement a feature allowing users to scroll through the list?
Or can mydockfinder implement a way of hiding certain unneeded items?

Thanks!!

**Comment by mydockfinder** [comment]
我记得我已经修复了，是1.7.1版本吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月23日(星期六) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] feature request: scroll through system tray icons (Issue #370)






我安装了这么多的工具，系统托盘菜单中的条目比屏幕上一次显示的还多。



列表中的最后一项只是被切断了，无法查看。

您能实现允许用户滚动列表的功能吗？
或者 my dock finder 可以实现一种隐藏不需要的项目的方法吗？

谢谢！

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到此消息是因为您订阅了此线程。留言 ID ***@***.*** have so many tools installed that there are more entries in the system tray menu than can be shown on the screen at once..The final items on the list are simply cut off, with no way to view them.

**Comment by twonth** [comment]
Thanks! I am using Steam version test 1.7.5.

**Comment by twonth** [comment]
Just clarifying that this is still an issue for me on 1.7.6.1. !

**Comment by twonth** [comment]
Fixed in 1.8. Closing. Thank you !!!

**Comment by mydockfinder** [comment]
下次 一定修复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月29日(星期五) 晚上9:10
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] feature request: scroll through system tray icons (Issue #370)





 
Just clarifying that this is still an issue for me on 1.7.6.1. !
 
&mdash;
